title: Sauka Kudzai # your name (or website title) here
logo: "/images/sauka.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Msc student, Gachon University. 
  <br>
  Researcher, Artificial Intelligence Security  lab, Gachon University.
  <br>
  <a href="https://www.researchgate.net/profile/Kudzai-Sauka">Researchgate</a> 
  <br>
  <a href="https://www.linkedin.com/in/kudzai-sauka/">LinkedIn</a> 
  <br>
  <a href="https://www.t.me/ZimPython/">Telegram Data science community</a>
  
markdown: kramdown
theme: jekyll-theme-minimal
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
